apiVersion: platform.confluent.io/v1beta1
kind: ControlCenter
metadata:
  name: controlcenter-ng
  namespace: confluent
spec:
  replicas: 1
  image:
    application: confluentinc/cp-enterprise-control-center-next-gen:2.2.0
    init: confluentinc/confluent-init-container:3.1.0
  dataVolumeCapacity: 10Gi
  dependencies:
    prometheusClient:
      url: http://controlcenter-ng.confluent.svc.cluster.local:9090
      authentication:
        type: basic
        basic:
          secretRef: prometheus-client-creds
    alertManagerClient:
      url: http://controlcenter-ng.confluent.svc.cluster.local:9093
      authentication:
        type: basic
        basic:
          secretRef: alertmanager-client-creds
    schemaRegistry:
      url: http://schemaregistry.confluent.svc.cluster.local:8081
    kafka:
      bootstrapEndpoint: kafka.confluent.svc.cluster.local:9071
  services:
    prometheus:
       image: confluentinc/cp-enterprise-prometheus:2.2.0
       authentication:
         type: basic
         basic:
          secretRef: prometheus-credentials
       pvc:
         dataVolumeCapacity: 10Gi
    alertmanager:
       image: confluentinc/cp-enterprise-alertmanager:2.2.0
       authentication:
         type: basic
         basic:
          secretRef: alertmanager-credentials
  configOverrides:
    server:
      - confluent.controlcenter.cmf.enable=True
      - confluent.controlcenter.cmf.url=http://cmf-service.confluent.svc.cluster.local:80